// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NWT2.Models;

namespace NWT2.Migrations
{
    [DbContext(typeof(PicerijaDbContext))]
    partial class PicerijaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NWT2.Entities.Adresa", b =>
                {
                    b.Property<Guid>("AdresaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Adrese")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("AdresaID");

                    b.ToTable("Adrese");
                });

            modelBuilder.Entity("NWT2.Entities.DetaljiNarudzbenice", b =>
                {
                    b.Property<Guid>("DetaljiNarudzbeniceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_DetNarudzbenice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Kolicina")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("NarudzbenicaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PicaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DetaljiNarudzbeniceID");

                    b.HasIndex("NarudzbenicaID");

                    b.HasIndex("PicaID");

                    b.ToTable("DetaljiNarudzbenica");
                });

            modelBuilder.Entity("NWT2.Entities.Dodatak", b =>
                {
                    b.Property<Guid>("DodatakID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Dodaci")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Cena")
                        .HasColumnType("smallint");

                    b.Property<string>("Naziv_dodatka")
                        .IsRequired()
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.HasKey("DodatakID");

                    b.ToTable("Dodaci");
                });

            modelBuilder.Entity("NWT2.Entities.EkstraDodaci", b =>
                {
                    b.Property<Guid>("Ekstra_dodaciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Dodaci")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DetaljiNarudzbeniceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DodatakID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Ekstra_dodaciID");

                    b.HasIndex("DetaljiNarudzbeniceID");

                    b.HasIndex("DodatakID");

                    b.ToTable("EkstraDodaci");
                });

            modelBuilder.Entity("NWT2.Entities.Kupac", b =>
                {
                    b.Property<Guid>("KupacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Kupca")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.HasKey("KupacID");

                    b.HasIndex("AdresaID");

                    b.ToTable("Kupci");
                });

            modelBuilder.Entity("NWT2.Entities.NacinPlacanja", b =>
                {
                    b.Property<Guid>("NacinPlacanjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_NacinPlacanja")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivNacinaPlacanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("NacinPlacanjaID");

                    b.ToTable("NaciniPlacanja");
                });

            modelBuilder.Entity("NWT2.Entities.Narudzbenica", b =>
                {
                    b.Property<Guid>("NarudzbenicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Narudzbenice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojNarudzbenice")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NacinPlacanjaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusDostaveID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoziloID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZaposleniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("datumPrijema")
                        .HasColumnType("date");

                    b.HasKey("NarudzbenicaID");

                    b.HasIndex("KupacID");

                    b.HasIndex("NacinPlacanjaID");

                    b.HasIndex("StatusDostaveID");

                    b.HasIndex("VoziloID");

                    b.HasIndex("ZaposleniId");

                    b.ToTable("Narudzbenice");
                });

            modelBuilder.Entity("NWT2.Entities.Pica", b =>
                {
                    b.Property<Guid>("PicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Pice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Cena")
                        .HasColumnType("smallint");

                    b.Property<string>("Kratak_opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.Property<string>("NazivPice")
                        .IsRequired()
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.HasKey("PicaID");

                    b.ToTable("Pice");
                });

            modelBuilder.Entity("NWT2.Entities.StatusDostave", b =>
                {
                    b.Property<Guid>("StatusDostaveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_statusa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivStatusa")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("StatusDostaveID");

                    b.ToTable("statusiDostave");
                });

            modelBuilder.Entity("NWT2.Entities.TipVozila", b =>
                {
                    b.Property<Guid>("TipVozilaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_tipVozila")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("vrstaVozila")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("TipVozilaID");

                    b.ToTable("TipoviVozila");
                });

            modelBuilder.Entity("NWT2.Entities.Vozilo", b =>
                {
                    b.Property<Guid>("VoziloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_Vozila")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetaljiVozila")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("EvidencioniBr")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("MarkaVozila")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<Guid>("TipVozilaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VoziloID");

                    b.HasIndex("TipVozilaID");

                    b.ToTable("Vozilo");
                });

            modelBuilder.Entity("NWT2.Entities.Zaposleni", b =>
                {
                    b.Property<Guid>("ZaposleniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_zaposlen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ZaposleniId");

                    b.HasIndex("AdresaID");

                    b.ToTable("Zaposleni");
                });

            modelBuilder.Entity("NWT2.Entities.DetaljiNarudzbenice", b =>
                {
                    b.HasOne("NWT2.Entities.Narudzbenica", "Narudzbenica")
                        .WithMany("DetaljiNarudzbenices")
                        .HasForeignKey("NarudzbenicaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NWT2.Entities.Pica", "Pica")
                        .WithMany()
                        .HasForeignKey("PicaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NWT2.Entities.EkstraDodaci", b =>
                {
                    b.HasOne("NWT2.Entities.DetaljiNarudzbenice", "DetaljiNarudzbenice")
                        .WithMany("EkstraDodaci")
                        .HasForeignKey("DetaljiNarudzbeniceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NWT2.Entities.Dodatak", "Dodatak")
                        .WithMany("EkstraDodaci")
                        .HasForeignKey("DodatakID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NWT2.Entities.Kupac", b =>
                {
                    b.HasOne("NWT2.Entities.Adresa", "Adresa")
                        .WithMany("Kupci")
                        .HasForeignKey("AdresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NWT2.Entities.Narudzbenica", b =>
                {
                    b.HasOne("NWT2.Entities.Kupac", "kupac")
                        .WithMany("Narudzbenice")
                        .HasForeignKey("KupacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NWT2.Entities.NacinPlacanja", "nacinPlacanja")
                        .WithMany("Narudzbenice")
                        .HasForeignKey("NacinPlacanjaID");

                    b.HasOne("NWT2.Entities.StatusDostave", "statusDostave")
                        .WithMany("Narudzbenice")
                        .HasForeignKey("StatusDostaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NWT2.Entities.Vozilo", "Vozilo")
                        .WithMany("Narudzbenice")
                        .HasForeignKey("VoziloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NWT2.Entities.Zaposleni", "Zaposleni")
                        .WithMany("Narudzbenice")
                        .HasForeignKey("ZaposleniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NWT2.Entities.Vozilo", b =>
                {
                    b.HasOne("NWT2.Entities.TipVozila", "TipVozila")
                        .WithMany("Vozila")
                        .HasForeignKey("TipVozilaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NWT2.Entities.Zaposleni", b =>
                {
                    b.HasOne("NWT2.Entities.Adresa", "Adresa")
                        .WithMany("Zaposleni")
                        .HasForeignKey("AdresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
